<?xml version="1.0" encoding="utf-8"?><Database Name="Db_one" Class="DB_oneDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Table Name="dbo.stud" Member="stds">
    <Type Name="std">
      <Column Name="rollno" Member="rollno1" Storage="_rollno" Type="System.Byte" DbType="TinyInt NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="name" Member="name1" Storage="_name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="address" Member="address1" Storage="_address" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
</Database>