#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AWT_Pract_Three
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Db_one")]
	public partial class DB_oneDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Insertstd(std instance);
    partial void Updatestd(std instance);
    partial void Deletestd(std instance);
    #endregion
		
		public DB_oneDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DB_oneDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DB_oneDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DB_oneDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<std> stds
		{
			get
			{
				return this.GetTable<std>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.stud")]
	public partial class std : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private byte _rollno;
		
		private string _name;
		
		private string _address;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onrollno1Changing(byte value);
    partial void Onrollno1Changed();
    partial void Onname1Changing(string value);
    partial void Onname1Changed();
    partial void Onaddress1Changing(string value);
    partial void Onaddress1Changed();
    #endregion
		
		public std()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="rollno", Storage="_rollno", DbType="TinyInt NOT NULL", IsPrimaryKey=true)]
		public byte rollno1
		{
			get
			{
				return this._rollno;
			}
			set
			{
				if ((this._rollno != value))
				{
					this.Onrollno1Changing(value);
					this.SendPropertyChanging();
					this._rollno = value;
					this.SendPropertyChanged("rollno1");
					this.Onrollno1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="name", Storage="_name", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string name1
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this.Onname1Changing(value);
					this.SendPropertyChanging();
					this._name = value;
					this.SendPropertyChanged("name1");
					this.Onname1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="address", Storage="_address", DbType="NVarChar(50)")]
		public string address1
		{
			get
			{
				return this._address;
			}
			set
			{
				if ((this._address != value))
				{
					this.Onaddress1Changing(value);
					this.SendPropertyChanging();
					this._address = value;
					this.SendPropertyChanged("address1");
					this.Onaddress1Changed();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
