//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AWT_Pract_Three
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Db_oneEntities1 : DbContext
    {
        public Db_oneEntities1(string conStr)
            : base("name=Db_oneEntities1")
        {
        }

        public Db_oneEntities1()
        {
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }

        internal object ToList()
        {
            throw new NotImplementedException();
        }

        public virtual DbSet<stud> studs { get; set; }
    }
}
